# Generated by Django 2.1.1 on 2018-09-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
