# Generated by Django 2.1.1 on 2018-10-03 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_profiles_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='fathersname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='profilesbank',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='login.Profiles'),
        ),
    ]
